### ISSUE TITLE
Adding a new source to the Umbraco backoffice collection cleared them all out

### ISSUE THREAD

**Issue by robertjf** [Matthew-Wise/Umbraco-CSP-manager#20]
I added www.gravatar.com to the Backoffice collection and pressed save, when I refreshed, the entire list was gone.

**Comment by robertjf** [comment]
Note - I don't yet know for sure whether they were actually deleted, or just can't display anymore...

**Comment by Matthew-Wise** [comment]
Hi @robertjf  Thanks for all the reports, Looks like I needed to click around the CMS a bit more, I did check this one with Seb and long term its going to be removed so I am going to take Digipex fix and make some ammends so that its only added to v 12 and below by default. Will update you again hopefully later today with a new release

**Comment by Matthew-Wise** [comment]
Version 1.1.0-alpha is building right now :)
